### ISSUE TITLE
搅拌机alpha版本的适配相关

### ISSUE THREAD

**Issue by ailenneko** [Arius-Cr/wire_ext_blender_fix_ime#10]
大佬 有考虑过兼容blender 4.2.0嘛?我是实验版本爱好者 喜欢用实验版本创作和研究新的渲染器 目前这款插件给予了我学习和研究blender的很大动力 要是能和我喜欢的4.2.0兼容那就更棒了

当然 如果因为某些原因 不可能让插件兼容4.2.0的话 我也是能理解的

**Comment by Arius-Cr** [comment]
要支持 Blender 的开发版是比较困难的，难点不在技术上，而是需要每天检查开发版中相关偏移量有没有改变，有改变就需要发布插件的新版，这个工作是比较繁琐。4.1.0 版和 4.1.0 beta 版（发布前最后一个 beta 版）在相关偏移量上就存在过差异。

或许会考虑加入一个”解除版本限制“的功能，让有需要的用户可以解除插件对 Blender 版本的限制，这样任何版本的 Blender 都可以使用插件，当然代价就是**可能**会导致 Blender 崩溃。我会研究一下有没有办法最大程度扩大对 Blender 版本的支持。

**Comment by Arius-Cr** [comment]
插件在 3.0.5 版开始支持每日更新版（alpha版），但仅支持当前周的周六或周日的每日更新版，支持新的每日更新版后就不支持旧的每日更新版。对每日更新版的支持和插件在 3.0.5 版引入的”自动更新内存偏移数据”功能是相关的，每日更新版和发布版的内存偏移数据同样保存在 src/native/blender.py 文件中。

**Comment by ailenneko** [comment]
你是我的神!
