### ISSUE TITLE
什么时候支持Mac啊

### ISSUE THREAD

**Issue by olafchou** [Arius-Cr/wire_ext_blender_fix_ime#12]
Mac的blender输入法切换经常失效，求Mac的插件

**Comment by Arius-Cr** [comment]
没有计划推出 Linux 或 MacOS 版。

插件在 Windows 系统上，是需要使用 Windows 自身的 API 来实现功能的，也就是插件本身不具备移植性，在另一个平台需要根据另一个平台的规则来办事，但是我完全没有这两个平台上的编程经验，因此对我来说移植需要消耗巨量的精力和时间，如果有熟悉 Linux 或 MacOS 编程的开发者，可以自行 fork 该仓库进行移植。
