### ISSUE TITLE
当同个工作区存在多个文本编辑器时，候选窗口没有出现在当前编辑中的编辑器内

### ISSUE THREAD

**Issue by ziweidao** [Arius-Cr/wire_ext_blender_fix_ime#13]
Blender版本：4.1.1
操作系统：Windows11
输入法：微软拼音
当存在左右两个文本编辑器，分别新建两个不同的文件时，编辑左边文本，候选窗正常显示在附近；而当编辑右边文本时，候选窗仍在左侧编辑器内，但输入完成后文本的确落入右侧编辑器。
如果是上下两个编辑器，候选窗口似乎只会显示在下方编辑器，其余更多编辑器并列的情形也会出现候选窗位置错误，但确切的规律尚不明确。

**Comment by ziweidao** [comment]
![屏幕截图 2024-06-07 202203](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/21352777/f8894c85-1283-4f94-807f-6a8a2750b501)

**Comment by Arius-Cr** [comment]
问题确认。

问题原因：候选窗口的位置会在重新绘制界面后更新一次，但同时存在两个文本编辑器时，后一个文本编辑器就会覆盖前一个文本编辑器定位候选窗口的结果。导致候选窗口总是由后一个文本编辑器决定。

**Comment by Arius-Cr** [comment]
已在 3.0.6 版中修复
