### ISSUE TITLE
不支持 blender 4.2.1

### ISSUE THREAD

**Issue by tianyong90** [Arius-Cr/wire_ext_blender_fix_ime#15]
blender 4.2.1 刚刚发布了，发现这插件不支持这一版本。blender 4.2 中使用体验非常好。
![image](https://github.com/user-attachments/assets/03452d82-5b35-42a1-bd2b-bb1a08ed3c59)

**Comment by Arius-Cr** [comment]
已更新内存偏移量数据文件，在插件的配置页面，点击“更新内存偏移量”即可自动获取最新的文件，然后插件就可以兼容 Blender 4.2.1 了。
