### ISSUE TITLE
大佬，崩溃bug反馈

### ISSUE THREAD

**Issue by CODEPROCODE** [Arius-Cr/wire_ext_blender_fix_ime#18]
具体崩溃的形式:

1，只要在用blender打开任何一个文件,处于读取状态中，此时连续点击鼠标和键盘,就近乎100%崩溃。

2，另外，在正常使用工作过程中，比如大型模型在切换对象模式和编辑模式时，如果多点按了几下鼠标，也会大概率崩溃

我的软硬件：操作系统是官方原版win10系统22h2,硬件配置是i5 13400f,32g内存,4060ti/16g.使用微软自带拼音输入法

blender为纯净全新安装.版本是blender4.x版本(4.2和4.3都试过),没开启任何额外插件(包括官方插件).仅仅从github下载并安装了最新版的wire_ext_blender_fix_ime

下面是我录制的blender崩溃过程。
链接: https://pan.baidu.com/s/1xMU3Q6lFgdaoFdrH0asZCw?pwd=3qfq      
提取码: 3qfq

**Comment by Arius-Cr** [comment]
问题确认。
问题原因：在文件完全加载前调用 Blender 的某些功能会导致 Blender 崩溃。
稍后再研究解决方案。

**Comment by Arius-Cr** [comment]
已在 3.0.12 版中完成修复

**Comment by CODEPROCODE** [comment]
感谢大佬的辛苦工作.
