### ISSUE TITLE
中文模式下，大量输入的性能问题

### ISSUE THREAD

**Issue by atticus-lv** [Arius-Cr/wire_ext_blender_fix_ime#2]
如题，当中文模式下使用大量键入，接收的数量越多反应越慢
https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/64118610/db38ec57-9f36-4073-8f86-d8acc11f13a4

**Comment by Arius-Cr** [comment]
”输入字符到达一定的数量后就无法输入“，这应该是输入法自身的设计。
你可以打开记事本，然后用同样的方式不断输入（建议用两个指头交替点击两个按键，可以同时测试是否存在按键被遗漏的问题），当字符到达一定数量后也会无法继续输入。
所以这应该不是插件原因导致的。

另外当输入的字符非常长的时候，根据插件本身的原理的确会在处理输入和删除字符的时候有轻微的卡顿（根据机器性能可能表现也不同），这个会考虑优化一下，但效果不一定明显。
而且一般来说，不会持续输入如此之长的文本，建议分开一个个词进行输入，因此目前的性能应该能够满足大部分的需求。

**Comment by atticus-lv** [comment]
是的，第一点是微软输入法的限制（所以很快就改了标题了hhh)
我还没有完全地看完代码，但考虑到即使在少量字符输入地时候，也能感知到和一般输入框地速度相应的差异，或许把mousemove事件的捕捉换成timer捕捉响应会更快一些

**Comment by Arius-Cr** [comment]
我这边使用输入法输入的时候感觉速度还可以，不至于明显感到很慢。
而且从视频里面看好像也没有很慢。
刚刚更新了 beta.2 版本，也优化了一下输入效率，你试试看有没有改善。

判断鼠标位置的代码在正在输入的时候是会暂时停止的，所以应该不是这个问题。

“timer捕捉”是指自己启动一个定时器然后在定时事件的时候判断吗？
说实话我以前是做网页前端的，C 和 Win32 也不是很熟悉，还望多多指教。

**Comment by Arius-Cr** [comment]
对了，曾经在测试的时候我自己遇到过输入文字的时候非常卡，甚至有按键会丢失的问题，需要重启Blender才好。
不过只发生了一次，并且之后也没有发生过了，所以不好找原因。

你遇到的”输入速度慢“是固定发生的还是偶然的？会发生按键丢失的情况吗？

**Comment by atticus-lv** [comment]
嗯，似乎我也遇到过按键丢失，不过好像之后也没怎么遇到过。输入速度慢是固定发生的。晚上我再测试下新版
