### ISSUE TITLE
启用插件后Blender自动保存失效

### ISSUE THREAD

**Issue by Lusuzucky** [Arius-Cr/wire_ext_blender_fix_ime#3]
Blender版本3.6.0
插件版本：2.0.0-beta.3

插件未启用时自动保存正常，插件启用后无论多久，blender都不会自动保存文件到临时目录，且到达自动保存时间之后禁用插件，文件会立即保存出来

插件版本1.0.0无此问题

**Comment by Arius-Cr** [comment]
自动保存失效的问题在 [beta.4](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/releases/tag/v2.0.0-beta.4) 已经修复。

Blender 在执行自动保存前会先检查是否存在模态操作正在运行，如果有则不执行自动保存，然后以每 10ms 的间隔检查一次，直到没有模态操作运行才执行。参考：Blender 源码的 wm_autosave_timer() 函数。
