### ISSUE TITLE
开启插件后，鼠标跳跃的问题

### ISSUE THREAD

**Issue by Lusuzucky** [Arius-Cr/wire_ext_blender_fix_ime#4]
插件版本：2.0.0-beta.5
软件版本：3.6.0

启用插件的情况下，按住鼠标拖动任意滑块/色盘，在特定时间之后，鼠标位置会重置到最开始点击的位置，并清空输入（过程中未松开鼠标左键）然后鼠标会显示（原本按下鼠标后光标会隐藏）松开鼠标前这个问题只会触发一次

![动画1](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/60422132/138f9e37-6a96-4d87-b0d9-092972950bdd)

在3D视图移动/旋转/缩放的时候，若鼠标光标穿过窗口边界折返，也会有同样的问题：

![动画2](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/60422132/d8936bf7-77d8-476a-9c69-b420140e0692)

**Comment by Arius-Cr** [comment]
问题已确认，目前没有快速的解决方案

**Comment by Arius-Cr** [comment]
该问题已在 [v2.0.0-beta.6](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/releases/tag/v2.0.0-beta.6) 中修复。

问题原因：“状态检查器”轮换时，会先结束自身的运行，而这个“结束”会导致Blender清空鼠标捕获后对鼠标移动位置的累计跟踪，导致鼠标跳跃或位置重置。
