### ISSUE TITLE
Feature Request: rime English model 

### ISSUE THREAD

**Issue by xbxcw** [Arius-Cr/wire_ext_blender_fix_ime#5]
感谢大佬的插件！
在使用过程中，有个问题，我使用的是小狼毫输入法，在中文模式下，一切正常。
当我想要，在输入框里输入英文时，我本能的切换到英文模式，但是却输入不了了，
现在只能通过中文模式，输入英文，然后shift转成英文，
![image](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/33365920/0deffd86-3ff7-42c0-9069-081491ad8ef4)
![image](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/33365920/79f43f42-c26e-45b9-a729-69b84ad255d5)
![image](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/33365920/1de41a43-e3c3-4730-8e5d-abb623a0d8f6)

小狼毫，是我到目前为止，找到可以用，右shift键切换中英文，并且没有乱七八糟东西的，输入法。
在blender 2.x时代 ，是没有问题的。
再次感谢大佬的插件

**Comment by Arius-Cr** [comment]
你好，非常感谢你的反馈。

我安装了小狼毫 v0.15.0 版，并且进行了测试，的确存在切换到英文输入状态后，无法输入的情况。
但是该情况无论插件是否安装或开启都存在，因此基本可以排除是插件的原因。

我到小狼毫的 GitHub 上看了一下，也有人反馈了和 Blender 相关的问题，症状是无法使用 Shift + A 之类的快捷键。

我觉得你到小狼毫的 GitHub 上反馈一下可能会更好，目前看上去向小狼毫方面反馈可能更快得到解决。

另外我在测试的时候发现了一个似乎可以让小狼毫在 Blender 中正常输入英文的方法：

- 首先必须至少安装一个其它的输入法，譬如微软拼音输入法。
- 打开 Blender，并且激活任意可以输入文字的输入框；
- 切换到非小狼毫的输入法，譬如微软拼音输入法；
- 然后按 Shift 键切换到**英文**输入状态；
- 再按 Win + Space 切换到小狼毫输入法。

这样似乎就可以在 Blender 中正常使用小狼毫输入中文和英文了。
效果好像能保持到程序关闭，只要中间不要再切换到其它输入法就可以了。

**Comment by xbxcw** [comment]
好的，感谢解答。

**Comment by Copy2Translator** [comment]
这个是小狼毫 win 版的问题，不过目前 0.15 还是比之前的好用了很多

**Comment by Arius-Cr** [comment]
插件的 3.0.0 版会意外让小狼毫输入法的英文输入模式重新“生效”。

但这并非修好了 BUG，而是越过了 BUG，这个 BUG 最终还是需要小狼毫自身修复才是稳妥的。

此处记录一下，问题产生的可能原因：

小狼毫 0.15.0 版的英文输入模式在 Blender 中无效的原因可能是，小狼毫输入法在切换输入模式后，并没有修改其输入模式的标记（通过 ImmGetConversionStatus 获取），也没有通过 WM_IME_NOTIFY 消息发送 IMN_SETCONVERSIONMODE 通知窗口。

而 Blender 通过 ImmGetConversionStatus 获取并通过 WM_IME_NOTIFY 跟踪输入法输入模式的改变。

小狼毫无论切换为那种输入模式（中/英），其表称的输入模式，即通过 API 提供给程序的输入模式，始终都是中文输入模式（尽管用户看到的是英文输入模式）。

而在中文输入模式时，Blender 基本只从输入法合成消息（WM_IME_COMPOSITION 之类）中获取输入，但处于“英文输入模式”的小狼毫不会产生输入法合成消息，所以最终导致问题的产生。

这个问题之所以在其它程序中不呈现，可能是因为 Blender 对按键输入消息的处理方式和常规的不同。

常规的程序是通过 WM_KEYDOWN 消息的特殊标记来识别输入走传统路径还是走输入法路径，常规方法是不需要理会输入法的输入模式的，所以输入法表称的输入模式不会妨碍其工作。

而 Blender 并没有使用常规的方式，而是需要依赖输入法表称的输入模式来判断输入走的路径。
