### ISSUE TITLE
未解决的问题

### ISSUE THREAD

**Issue by ailenneko** [Arius-Cr/wire_ext_blender_fix_ime#6]
我使用win11的微软输入法的 中文输入模式 的时候,打不了大写字母和标点符号,需要手动切换到英文模式才能打出来,请问这个问题可能修复或者可以修复嘛?能修复的话万分感谢!

大写字母我是按大小写切换键打的 不是按shift 按shift是可以打出来大写的

**Comment by Arius-Cr** [comment]
该问题已由插件的 3.0.0 版修复。

修复方法：判断按键是否由输入法处理，如果不是，则先停用输入法，然后让Blender处理按键，然后再重新启用输入法，以避开 Blender 原先的处理方式。
