### ISSUE TITLE
4.0.2报错

### ISSUE THREAD

**Issue by HYE-cmyk** [Arius-Cr/wire_ext_blender_fix_ime#7]
![微信图片_20231228092221](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/136038504/cd3f9312-0b7c-4f14-8518-adb07cb70bf1)
大佬，问题如图，打勾就会显示报错

**Comment by Arius-Cr** [comment]
该问题已通过BiliBili的SNS系统沟通解决。

原因是用户使用了第三方打包的插件安装包，该安装包的目录结构存在问题，使得插件安装的时候，以“wire_ext_blender_fix_ime-2.0.1”作为文件夹名称，而插件文件夹需要作为Python模块名称来识别，不能存在点号（.），最终导致插件加载时找不到模块而报错。

可以通过删除文件夹名称中的点号（.）来排除错误，或者安装时使用第一方或合格的第三方安装包来解决问题。
