### ISSUE TITLE
编辑文字对象后，无法操作。然后报错

### ISSUE THREAD

**Issue by 745692208** [Arius-Cr/wire_ext_blender_fix_ime#8]
新建了一个Text对象，编辑了下文字，输入了个R，然后切回物体模式后，无法操作。然后报错。

![QQ截图20240116105442](https://github.com/Arius-Cr/wire_ext_blender_fix_ime/assets/34736964/0d2d5539-85e6-4f34-9d3b-c91b88142b3e)

**Comment by Arius-Cr** [comment]
这边简单根据你提供的信息操作了一下，但没能复现问题。

你遇到的这个问题是偶发的还是必定会发生的？
如果必定会发生的话，请详细描述一下复现的步骤（譬如“编辑了下文字”这步骤是触发问题的必要条件还是不必要条件，如果是必要条件，是进行了怎样的编辑才能触发问题之类...）。

另外请补充一下你使用的Blender和本插件的版本信息。

此外是发现了另外的问题，就是修饰键的状态偶然会有问题，譬如Shift键已经释放，但是Blender依然认为Shift键是按下的，然后你按G的时候，Blender会认为你按的是Shift+G，有时看上去像是没反应或者反应错乱（再按一下Shift可以解决）。这个问题目前还在探究中。

虽然遇到上述的问题，但没有报错，不一定是你遇到的问题。
